//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mx.Amib.Sistemas.Credencializacion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mx.Amib.Sistemas.Credencializacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F2DEDE.
        /// </summary>
        public static string ColorBackgroundErrorStatePanel {
            get {
                return ResourceManager.GetString("ColorBackgroundErrorStatePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F2DEDE.
        /// </summary>
        public static string ColorBackgroundErrorTextbox {
            get {
                return ResourceManager.GetString("ColorBackgroundErrorTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #d9edf7.
        /// </summary>
        public static string ColorBackgroundInfoStatePanel {
            get {
                return ResourceManager.GetString("ColorBackgroundInfoStatePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string ColorBackgroundTextbox {
            get {
                return ResourceManager.GetString("ColorBackgroundTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string ColorBackgroundWindow {
            get {
                return ResourceManager.GetString("ColorBackgroundWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A94442.
        /// </summary>
        public static string ColorForegroundErrorStatePanel {
            get {
                return ResourceManager.GetString("ColorForegroundErrorStatePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A94442.
        /// </summary>
        public static string ColorForegroundErrorTextbox {
            get {
                return ResourceManager.GetString("ColorForegroundErrorTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #31708f.
        /// </summary>
        public static string ColorForegroundInfoStatePanel {
            get {
                return ResourceManager.GetString("ColorForegroundInfoStatePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        public static string ColorForegroundTextbox {
            get {
                return ResourceManager.GetString("ColorForegroundTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        public static string ColorForegroundWindow {
            get {
                return ResourceManager.GetString("ColorForegroundWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DegradadoTituloAplicacion {
            get {
                object obj = ResourceManager.GetObject("DegradadoTituloAplicacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FondoTitulo {
            get {
                object obj = ResourceManager.GetObject("FondoTitulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconBack {
            get {
                object obj = ResourceManager.GetObject("IconBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconFilesave {
            get {
                object obj = ResourceManager.GetObject("IconFilesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconFinish {
            get {
                object obj = ResourceManager.GetObject("IconFinish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconForward {
            get {
                object obj = ResourceManager.GetObject("IconForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconGoToPage {
            get {
                object obj = ResourceManager.GetObject("IconGoToPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconIdentity {
            get {
                object obj = ResourceManager.GetObject("IconIdentity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconoAplicacion {
            get {
                object obj = ResourceManager.GetObject("IconoAplicacion", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconReload {
            get {
                object obj = ResourceManager.GetObject("IconReload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconStart {
            get {
                object obj = ResourceManager.GetObject("IconStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconUndo {
            get {
                object obj = ResourceManager.GetObject("IconUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogotipoAmib {
            get {
                object obj = ResourceManager.GetObject("LogotipoAmib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconDefault {
            get {
                object obj = ResourceManager.GetObject("MenuIconDefault", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MenuIconPQPause {
            get {
                object obj = ResourceManager.GetObject("MenuIconPQPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MenuIconPQPlay {
            get {
                object obj = ResourceManager.GetObject("MenuIconPQPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MenuIconPQStop {
            get {
                object obj = ResourceManager.GetObject("MenuIconPQStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MenuIconPQTrash {
            get {
                object obj = ResourceManager.GetObject("MenuIconPQTrash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconPrinterConfig {
            get {
                object obj = ResourceManager.GetObject("MenuIconPrinterConfig", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconPrinterLogging {
            get {
                object obj = ResourceManager.GetObject("MenuIconPrinterLogging", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconPrinterQueue {
            get {
                object obj = ResourceManager.GetObject("MenuIconPrinterQueue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconSustentantes {
            get {
                object obj = ResourceManager.GetObject("MenuIconSustentantes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon MenuIconTemplateConfig {
            get {
                object obj = ResourceManager.GetObject("MenuIconTemplateConfig", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca constraseña.
        /// </summary>
        public static string MessageLogInErrorBlankPassword {
            get {
                return ResourceManager.GetString("MessageLogInErrorBlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca nombre de usuario.
        /// </summary>
        public static string MessageLogInErrorBlankUserName {
            get {
                return ResourceManager.GetString("MessageLogInErrorBlankUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario y contraseña no coinciden con ningun registro.
        /// </summary>
        public static string MessageLogInErrorCredentialsNotFound {
            get {
                return ResourceManager.GetString("MessageLogInErrorCredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener datos de autenticación.
        /// </summary>
        public static string MessageLogInErrorFetchingData {
            get {
                return ResourceManager.GetString("MessageLogInErrorFetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro del usuario aún no ha sido autorizado.
        /// </summary>
        public static string MessageLogInErrorIsLockedOut {
            get {
                return ResourceManager.GetString("MessageLogInErrorIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido bloqueado.
        /// </summary>
        public static string MessageLogInErrorNonApproved {
            get {
                return ResourceManager.GetString("MessageLogInErrorNonApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere un momento....
        /// </summary>
        public static string MessageLogInProcessing {
            get {
                return ResourceManager.GetString("MessageLogInProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido al Sistema de Credencialización!.
        /// </summary>
        public static string MessageLogInWelcome {
            get {
                return ResourceManager.GetString("MessageLogInWelcome", resourceCulture);
            }
        }
    }
}
